### ISSUE TITLE
Remove wlr_seat_client_for_wl_client

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1023]
This function assumes a client only binds once to the seat. This isn't the case of Firefox on Wayland.

**Comment by martinetd** [comment]
I was thinking we could not allocate a new wlr_seat_client everytime there's a new bind; that means changing the struct to hold a list of "creator" resources instead of a single pointer.
The create function would check if it exists first and only create the wayland resource to add to the existing struct if it does. The downside is that we won't be able to tell which pointer/keyboard comes from which binding, but I think that's OK?

**Comment by emersion** [comment]
Yeah, that's a good idea.
