### ISSUE TITLE
Advertise wl_output’s refresh rate on the Wayland backend

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#1273]
Currently when running either sway or rootston, `weston-info` reports a refresh rate of 0 Hz on the `wl_output`, which is obviously wrong. It would make sense to report the same one as the parent compositor’s `wl_output`, or 60 Hz as a fallback (e.g. if this one too reports 0 Hz).

It could make sense to re-emit the mode when the compositor’s surface is moved to an output with a different refresh rate, in case the outer compositor has more than one output exposed.

**Comment by emersion** [comment]
I'm against this for several reasons:

* The Wayland protocol [has been updated](https://github.com/wayland-project/wayland/commit/504db9d8e5d3a6de4abbbb0ae11a82fd81b3771f) to allow zero refresh sizes for outputs that are e.g. virtual. I think we should do the same for refresh rate. I'll try to send a patch.
* FreeSync outputs won't have a fixed refresh rate anyway, so it makes sense to do this change outside the scope of virtual outputs.
* A Wayland window can be on multiple outputs. We don't know which one the compositor has decided to "pin" the surface on.
* Clients shouldn't use this value anyway
* The other parts of the mode _must_ be faked anyway, since the size in pixel of the surface is different  from the parent compositor's output size

**Comment by linkmauve** [comment]
For reference: https://lists.freedesktop.org/archives/wayland-devel/2018-September/039496.html

I quite agree with that direction, but imo this should become a hint instead of being made optional, for legacy clients.  Both the FreeSync thing and the multiple output things would benefit from that, setting the maximum value possible sounds acceptable to me.

**Comment by SirCmpwn** [comment]
I think zero is fine. In fact, I'd consider setting it to zero for all outputs, because I don't want to encourage users to render frames at any rate other than when frame events come in.

**Comment by emersion** [comment]
Yeah, instead of adding workarounds in the compositor, buggy clients should be fixed.
