### ISSUE TITLE
monitors on and off does not work

### ISSUE THREAD

**Issue by trangiusarien** [swaywm/wlroots#1436]
I use two 4k monitors, with a AMD GPU card and two separate DP outputs from the card (not using DP MST that is).

When I turn dp1 off, the workspace ends up on dp2 as expected. When I start sway without dp1 on (only dp2), and then turn dp1 on, it works. However, if I turn it off and then on again, it is just blank and the workspace dissapears from dp2 (as if it is going into dp1 but noting is displayed there). If I then turn dp1 off again, it takes quite a while and then I get the workspace back on dp2. I have to restart sway to get both monitors working again...

Here is a 'sway -d >sway.log 2>&1' ouput: https://pastebin.com/EpMtqBtB - Here I just started sway, turned off the monitor, waited 30s, turned it on and waited but the monitor was just blank. Turning sway off after this took quite a while, and usually it exits immediately.

**Comment by lord-re** [comment]
What if you only start with one monitor and shut it off and on ?

**Comment by trangiusarien** [comment]
What happens when I start with only one monitor and shut it off and on, is that when it turns back on again, I only see a black screen with the mouse cursor in the middle but nothing else.

Here is the output from 'sway -d >sway.log 2>&1' with only one monitor:
[sway.log](https://github.com/swaywm/wlroots/files/2700010/sway.log)

**Comment by lord-re** [comment]
I have the same behavior with only 1 monitor.

In tty1 i launch sway. In tty2 i launch : sleep 30&& killall sway.
I go back to tty1. I switch off then on the monitor.

Sway doesn't respond at all with only the cursor and a black screen.
After the 30 seconds sway is killed and i can relaunch sway without rebooting.

So shutting down a monitor freezes sway which can't accept any input nor display anything meaningful.

**Comment by drbawb** [comment]
Out of curiosity which kernel and AMD GPU are you using? I ran into a similar problem a while back that ended up being fixed in Linux 4.20. The issue I was having was that if I power cycled my DP display it would remain black (occasionally with a cursor) and the kernel log would fill up w/ bug checks saying `flip_done timed out`. I could still SSH into the machine and kill sway, occasionally I could switch to another tty.

I would look check [this patch](https://github.com/torvalds/linux/commit/a81a7c9c9ea3042ab02d66ac35def74abf091c15#diff-8493534962e183938c0fe4da9c92dd03L228) and compare it to the vendor/device ID you get from  `lspci` for your GPU. If that patch affects your GPU, and your distro hasn't backported that fix to your kernel [along with the corresponding firmware blobs](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/) from ~2018-12-14 that may explain the issue you're seeing.

**Comment by lord-re** [comment]
Hooo ! You are right.
I upgraded from 4.19 to 4.20 and now it works as expected.

**Comment by trangiusarien** [comment]
Ah, it works for me too now with 4.20. I close this issue! :)
