### ISSUE TITLE
DRM atomic backend

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#1688]
To be able to properly implement https://github.com/swaywm/wlroots/issues/1640, we'll need to use many of the atomic-specific features (e.g. TEST_ONLY).

The current DRM backend makes this difficult because it has support for both the legacy API and the new atomic one. This makes implementing atomic-only feaures difficult because we use the atomic backend without taking advantage of atomicity.

I think the best solution would be to add a new atomic-only DRM backend.

**Comment by ascent12** [comment]
Yup, I've been thinking the same thing in the back of my mind for a long time.

**Comment by panaman67** [comment]
@emersion Would it be possible to remove the legacy API instead of writing a whole new backend? Asking to learn.

**Comment by emersion** [comment]
The legacy API is still used by a bunch of drivers, so we can't drop it yet.

**Comment by ascent12** [comment]
For anybody that is interested at looking at some self-contained atomic DRM code, without all of the extra shit from wlroots/weston, you can see a nice commented example here: https://gitlab.freedesktop.org/daniels/kms-quads

**Comment by emersion** [comment]
Ah, nice. Also related:

* https://github.com/ascent12/drm_experimentation
* https://github.com/emersion/drm-playground

**Comment by Emantor** [comment]
If atomic and legacy are separated, do we want to retain a `common` folder with implementations common to both backends? I'm interested in the separation because I want to use page_flip_handler2 with `crtc_id` to investigate swaymw/sway#4149 and find out where this erronous flip comes from. Since we pass in a `wlr_connector` and this somehow gets freed before the pending flip is executed I took a look into the weston implementation which always passes its backend structure in the atomic version. This allows them to detect unexpected pageflips w/o crashing the compositor.

**Comment by emersion** [comment]
>do we want to retain a common folder with implementations common to both backends?

Depends what we can share and what we want to share. We probably want to improve the atomic parts of the current DRM backend. Also I'm not sure if we want renderer v6 to happen before this.

>I'm interested in the separation because I want to use page_flip_handler2 with crtc_id to investigate swaymw/sway#4149 and find out where this erronous flip comes from. Since we pass in a wlr_connector and this somehow gets freed before the pending flip is executed I took a look into the weston implementation which always passes its backend structure in the atomic version. This allows them to detect unexpected pageflips w/o crashing the compositor.

Ah, that's probably a good idea indeed.

**Comment by ascent12** [comment]
>I'm interested in the separation because I want to use page_flip_handler2 with crtc_id

`page_flip_handler2` isn't tied to atomic. `drmModePageFlip` (the legacy function) will still trigger it. It's just that atomic is the only one that can submit multiple page flips at the same time, which is why it would want it.

I'll definitely accept patches changing it over to `page_flip_hander2`.

>Also I'm not sure if we want renderer v6 to happen before this.

Most DRM backend changes probably could be done independently.

**Comment by emersion** [comment]
>I'll definitely accept patches changing it over to page_flip_hander2.

Not all drivers support `page_flip_hander2`. I think the capability is `DRM_CAP_CRTC_IN_VBLANK_EVENT`.

**Comment by ascent12** [comment]
It's purely DRM core thing, so drivers don't need to support it separately. It's unconditionally supported:
https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/drm_ioctl.c#L296-L298
Basically, the cap just allows us to test if we're running on an old kernel, and we've never particularly cared about long backwards compatibility promises. The blame says those lines were added 2 years ago.

**Comment by emersion** [comment]
Okay. I guess we could still check for the cap and hard fail if it isn't supported.

**Comment by emersion** [comment]
The DRM backend now has better atomic support, no need for an additional backend.

We also use `page_flip_hander2`.
