### ISSUE TITLE
[request] support compiling with wayland/wayland-protocols 1.15

### ISSUE THREAD

**Issue by mkosem** [swaywm/wlroots#1772]
Some distributions, like RHEL8, don't have quite so new Wayland as this project requires (both are 1.15).  It's possible to get wlroots/sway compiled on that distro, but only after reverting a number of commits related to the selection/input/output.  Since RHEL8 is fairly current, and will be around for quite a while, it seems reasonable that libraries like this should support it without needing to revert commits like that (via macros, etc.). Any chance you'd be willing to dial back the required wayland versions to expand the audience?  This in awesome WM, but I fear that it won't be within my capabilities to revert changes in this manner by myself as the code base continues to mature.

**Comment by ascent12** [comment]
It's always been wlroots' policy to require very recent versions of our dependencies. Enough stuff is changed/added often enough that it becomes quite a large maintenance burden to try and support old versions (`#ifdef`s everywhere really suck) and I doubt they're going to receive much testing, if any. While Debian and RHEL releases right now are rather "fresh", at the later part of their life, we're talking about dependencies that are over 3 years old, which is an insanely long time for this type of thing.

If you want to use wlroots/sway on such a distro, you're just going to need to compile recent versions of our dependencies too. wayland-protocols is especially harmless, because it's literally just a bunch of XML files.

**Comment by mikeandmore** [comment]
I understand depending on old libraries and platforms can be challenging. However, until RHEL 9 there won't be any changes for wayland 1.16, as RHEL needs to maintain its stable ABI. This means that swaywm won't be available to these platforms until around 2025.

Is it a good idea to create a port/backport branch just for wayland 1.15?

**Comment by JonasKs** [comment]
As a RHEL8 user I’d be interested in this too.
I’m kind of hesitant to upgrade my wayland to 1.16.0.

**Comment by ddevault** [comment]
Why would you hesitate? Releases are backwards compatible. Our policy has been stated, so quit bothering us.
