### ISSUE TITLE
Add support for X11 _MOTIF_WM_HINTS and WM_NORMAL_HINTS

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#178]
This includes features such as window minimum size and window decorations.

See https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html

wlc doesn't support these.

**Comment by acrisci** [comment]
Look at i3 [`src/window.c:314`](https://github.com/i3/i3/blob/next/src/window.c#L314) `window_update_motif_hints()` for some detailed info on motif hints.

**Comment by bew** [comment]
Maybe already answered somewhere, but this kind of feature is something that should be handled by the program using this library, not directly by the library. Or is it?

**Comment by SirCmpwn** [comment]
Well, wlroots provides Xwayland support. In my opinion, we should treat xwayland like another shell, ala xdg_shell or wl_shell. We should expose a fair bit of information we glean from each surface and give an interface that is reasonably similar to the other shells.

**Comment by acrisci** [comment]
Yes, we should let the app interpret these because interpretation is quite application specific.

For an example interpretation in the tiling context, look at i3 [src/manage.c:81](https://github.com/i3/i3/blob/next/src/manage.c#L81) `manage_window()`. Since there is nothing in any X11 spec that has to do with tiling, we came up with our own rules for these hints and eventually settled on something that does a pretty good job of interpreting them. But there was some argument over some of the more subtle points that could have gone either way.

**Comment by SirCmpwn** [comment]
Well, wlroots should definitely provide an interface to manipulating this information. I'd like to avoid having to have wlroots users write xkb code directly, within reason.
