### ISSUE TITLE
Build errors in rdp backend

### ISSUE THREAD

**Issue by nedludd** [swaywm/wlroots#1941]
I'm getting this when I build against the latest `freerdp-git` package (in Arch)

```
./backend/rdp/peer.c: In function ‘rdp_peer_context_new’:
../backend/rdp/peer.c:256:2: error: ‘nsc_context_set_pixel_format’ is deprecated [-Werror=deprecated-declarations]
  256 |  nsc_context_set_pixel_format(context->nsc_context, PIXEL_FORMAT_BGRA32);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/winpr2/winpr/synch.h:29,
                 from /usr/include/winpr2/winpr/wlog.h:33,
                 from /usr/include/freerdp2/freerdp/codec/color.h:26,
                 from ../include/backend/rdp.h:3,
                 from ../backend/rdp/peer.c:10:
/usr/include/freerdp2/freerdp/codec/nsc.h:47:36: note: declared here
   47 |  FREERDP_API WINPR_DEPRECATED(BOOL nsc_context_set_pixel_format(NSC_CONTEXT* context,
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/winpr2/winpr/winpr.h:53:31: note: in definition of macro ‘WINPR_DEPRECATED’
   53 | #define WINPR_DEPRECATED(obj) obj __attribute__((deprecated))
      |                               ^~~

```

Got it to work by disabling freerdp, but not sure what that effect that has on Sway, which did build cleanly after this.

**Comment by colemickens** [comment]
Freerdp has marked that function deprecated since the latest stable release. There's an easy fix - I actually patch wlroots and friends and build against HEAD freerdp (since freerdp-stable doesn't actually work under Wayland). It's a very simple patch I apply after cloning, before building: https://github.com/colemickens/nixpkgs-wayland/blob/22ea9e08ce2ef6817b722fe80c757ab35ed227c5/pkgs/wlroots/default.nix#L22

**Comment by emersion** [comment]
Can you send this as a pull request, @colemickens?

**Comment by colemickens** [comment]
Since the backend was dropped, I won't send a PR and I think this can be closed.

(Is there a wayvnc equivalent for RDP underway, maybe?)
