### ISSUE TITLE
Replace logind CanGraphical with udev monitoring

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2093]
See https://lists.freedesktop.org/archives/systemd-devel/2020-April/044245.html

**Comment by ascent12** [comment]
One way to do this is to make `wlr_session` a type that the user is expected to deal with during initialization.

1. User creates a wlr_session
2. Listens for a "device added" signal
3. Creates a DRM backend from the device, possibly mulitple
4. Starts the backend

This would also help out with DRM device hotplugging, but is quite a breaking change. It doesn't fit the X11/Wayland backend initialization either, because they have no need for `wlr_session`. We could make the user just deal with the DRM backend acting differently, or add some kind no-op `wlr_session` that X11/Wayland would use.

Another easier but crappier way is to just block inside the `wlr_session`, waiting for a device to show up.

**Comment by emersion** [comment]
I don't know whether multiple DRM backends is a good idea. Could just have one DRM backend for all DRM devices.

**Comment by ascent12** [comment]
We still need a way to notify the user that a new device has appeared or disappeared. They may want to selectively enable/disable devices based on user configuration.

**Comment by emersion** [comment]
That's a good point. They also may want not to use udev and have a custom list of DRM devices to open.
