### ISSUE TITLE
fbdev backend?

### ISSUE THREAD

**Issue by calvinkosmatka** [swaywm/wlroots#2126]
I want to use Sway directly in Hyper-V, but (as far as I'm aware) Hyper-V doesn't have a DRM graphics driver, only hyperv_fb. My workaround right now is to use the HEADLESS backend and wayvnc, but this is a bit cumbersome. It looks like an fbdev backend has been brought up a couple times (#9 #642), is this still being considered/being worked on? I'm willing to take a look at developing this.

**Comment by emersion** [comment]
Would be a lot better to just add DRM support to Hyper-V.

**Comment by ascent12** [comment]
I just don't think it's worth maintaining an fbdev backend. It **really** doesn't fit the wlroots-managed buffer thing I want to be done with renderer v6, and it going to be hacked in and slow at best.
Looking at weston's fbdev backend, it's been severely neglected because nobody really cares about it, and its removal has been discussed several times. I think it would be even more neglected in wlroots.

Doing everybody a favour and writing a DRM driver for previously fbdev-only things is much better. They've really made writing atomic DRM drivers much easier than it used to be, but still isn't something I'd call trivial.

**Comment by calvinkosmatka** [comment]
Makes sense to me, closing this out.

**Comment by mskarbek** [comment]
@calvinkosmatka I have tested Sway on Hyper-V with this patch - https://lists.freedesktop.org/archives/dri-devel/2021-February/297566.html
Works fine.
