### ISSUE TITLE
Compositors may need to send no-op configure events

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2330]
When the client sends a `set_maximized` or `set_fullscreen` request (or one of the `unset` variants), the protocol states that the compositor must send a `configure` event, even if it's a no-op because the compositor refuses.

We should at least document this properly, because this can be a little surprising and cause frozen clients.

Ideally wlroots should also help with this. However wlroots can't schedule a configure event right away, because this breaks asynchronous configure events (in case the compositor defers the decision).

See https://github.com/swaywm/sway/pull/5544

**Comment by RPigott** [comment]
What if this was handled in `wlr_xdg_toplevel_set_maximized`, for example? That is a function the compositor would already call to indicate it has made a decision, but the issue is wlroots does _extra_ work in this case to compare the states when that's really unnecessary, since it has to schedule a configure anyway. So instead of

https://github.com/swaywm/wlroots/blob/aaf490d794bd077330c306face305f4a87de5809/types/xdg_shell/wlr_xdg_toplevel.c#L584

We would use `wlr_xdg_surface_schedule_configure` to skip the comparison there for those requests in which scheduling a configure is required regardless.

The difference is that for compositors that don't care about maximizing like sway, instead of not implementing set_maximized they'd be required to implement a stub handler that just returns false, e.g. `wlr_xdg_toplevel_set_maximized(surface, false)` to let wlroots know it's done considering the client's request. Compositors that don't do that would get the same old buggy behavior, so we can document that requirement somewhere. As long as compositors implement handlers like they normal, they will get the correct Wayland behavior because wlroots will know when a configure is required or not.

Does that sounds good? I can draft a pull for wlroots/sway if does.

**Comment by emersion** [comment]
So far we've allowed compositors to repeatedly call e.g. `wlr_xdg_toplevel_set_maximized` without caring about the current state. This has allowed compositors to blindly call it even if the toplevel had the right state. Your change would break that (not saying it's necessarily a bad thing).

Note that the guarantee in the protocol to always send a `configure` event after a `set_maximized` request is racy anyways:

- Compositor sends `configure` on its own
- Client sends `set_maximized`
- Compositor sends `configure` in response to the request
- Client receives the first `configure` event, assumes it's a response to its `set_maximized` request

The client has no way to map `configure` events to `set_*` requests (if any).

**Comment by RPigott** [comment]
> So far we've allowed compositors to repeatedly call e.g. wlr_xdg_toplevel_set_maximized without caring about the current state. This has allowed compositors to blindly call it even if the toplevel had the right state. Your change would break that 

Yeah, I see how that's a drawback. That said, I think the state comparison is most helpful when responding to client requests. If the compositor spuriously calls set_maximized, it seems a more likely it chose to do so because it thinks the client is not already maximized. I get that for most client requests it may be helpful to let wlroots figure it out what to do, except in these two specific cases wlroots' state comparison hurts rather than helps. That's why if we don't want to change the api I think this is the best solution.

If api can change, I feel like a good simple solution might be just having a "force" argument in xdg_set_* calls. That way when the compositor already knows the client state, or knows it does not matter such as in the case of maximize and fullscreen it can indicate to wlroots to forgo the check. Then you could literally just add `false` to all your xdg_set_* calls to get the old behavior and force the configure in the few cases you want. Compositors would then need to know to handle maximize/fullscreen, but it's a simple change at least.

**Comment by emersion** [comment]
Hmm, I wonder if we can make it easy for compositors. Maybe we can set a "dirty" flag in the `set_*` request handlers in wlroots, and make all `wlr_xdg_toplevel_set_*` calls force-send a configure if the dirty flag is set?

**Comment by RPigott** [comment]
That sounds good to me.

**Comment by inclement** [comment]
I just hit this problem while trying to decline fullscreen requests, which didn't work since the configure event response was optimised away. I'd like to get it fixed - do I understand correctly that it would be acceptable to give the `set_{fullscreen,maximize,...}` a boolean dirty flag which if set forces the configure event regardless of the current state?

@RPigott are you still working on https://github.com/swaywm/wlroots/pull/2361 or do you mind if I make a PR for this change?

**Comment by RPigott** [comment]
Go for it.
