### ISSUE TITLE
wlroots with directfb backend?

### ISSUE THREAD

**Issue by lonnietc** [swaywm/wlroots#2346]
Hello,

Is it possible to use wlroots with the directfb (or other direct framebuffer) backend library instead of DRM, or Xorg?

Thanks

**Comment by emersion** [comment]
No, wlroots only supports DRM, Wayland and X11 backends.

A third-party backend could implement it. Keep in mind that right now wlroots requires GLESv2.

**Comment by lonnietc** [comment]
Hi Simon,

Thanks for the message back so quickly.

I actually have the challenge that I am trying to basically have a graphics
manager that is absolutely as small as possible just to display a single
application "wlfreerdp" which is the Wayland compiled RDP client from the
FreeRDP project on a FreeBSD.

As such, I did not want to use Xorg (X11) since it is huge and did not know
of any other possible options except to look at possibly Wayland with the
Weston compositor but was just recently told that the Sway project might be
of some help.  I do not know a lot about DRM but am also wondering if pure
Wayland might be an option instead.

I am testing on a Debian 10 (amd64) system inside a VirtualBox VM running
FreeBSD and the DRM stuff would not seem to run since it was looking for a
GPU I would guess and that is not present in VirtualBox.

Any suggestions would be helpful
Cheers
Lonnie

**Comment by progandy** [comment]
The linux kernel has a KMS driver for virtualbox: https://cateee.net/lkddb/web-lkddb/DRM_VBOXVIDEO.html
I believe vboxvideo is being ported to FreeBSD as part of the v5 branch of drm-kmod

https://www.freshports.org/graphics/drm-kmod/
https://github.com/FreeBSDDesktop/kms-drm/tree/drm-v5.0
http://freebsd.1045724.x6.nabble.com/Accelerated-graphics-in-vbox-6-td6330911.html#a6330946

**Comment by lonnietc** [comment]
Thanks again,

I will definitely go digging into this right now.

Appreciate the input
Cheers,
Lonnie

**Comment by jbeich** [comment]
devel/directfb doesn't support FreeBSD framebuffer API, only SDL and X11 backends. However, devel/sdl12 still has [vgl(3)](https://man.freebsd.org/vgl/3) backend but it wasn't stable for me.

drm-v5.0 was only supported on 13.0-CURRENT via graphics/drm-devel-kmod but since a few updates vboxvideo is broken, see https://github.com/freebsd/drm-kmod/issues/16. The plan is to quickly catch up to Linux 5.4 (LTS) and stabilize in hope  to merge LinuxKPI bits to FreeBSD 12.2. Currently, FreeBSD 12.1 only supports DRM from Linux 4.16 while FreeBSD 11.* only supports 4.11.

Better try on real hardware as i915kms and amdgpu are well supported.

**Comment by lonnietc** [comment]
Hi Jan,

Thanks for the update on this.

I just installed FreeBSD 12.1 on real hardware.  It currently has the Xorg
and Xfce desktop installed by default but I am very interested to see if I
can test Wayland sway on it.  Not sure if I have to remove Xorg and Xfce
and start with no desktop to get things going, or if they can co-exist.
This I am still researching.

As soon as I can find some documentation on how to install some of it on
FreeBSD then I will give it a try.
