### ISSUE TITLE
display corruption with wlroots master 20201203 on nouveau

### ISSUE THREAD

**Issue by xmixahlx** [swaywm/wlroots#2509]
with wlroots master 20201203 and sway (using nouveau with 2013 MBP 15") i have display corruption making sway completely unusable, requiring a tty kill. pulling wlroots tag 0.12.0 solves this problem.

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by emersion** [comment]
Bleh, selected the wrong comment in the auto-reply dialog. Sorry about that.

Please provide full debug logs.

**Comment by emersion** [comment]
BTW, anything in dmesg? I just tried multi-GPU with nouveau (old NVIDIA card) and got a kernel oops.

**Comment by xmixahlx** [comment]
[sway_wlroots-master-3_xwayland-disabled_and_waybar-disabled.log](https://github.com/swaywm/wlroots/files/5683875/sway_wlroots-master-3_xwayland-disabled_and_waybar-disabled.log)
[sway_wlroots-master-2_xwayland-disabled.log](https://github.com/swaywm/wlroots/files/5683876/sway_wlroots-master-2_xwayland-disabled.log)
[sway_wlroots-master-1.log](https://github.com/swaywm/wlroots/files/5683877/sway_wlroots-master-1.log)
[sway_wlroots-0.12.0-3.log](https://github.com/swaywm/wlroots/files/5683878/sway_wlroots-0.12.0-3.log)

swaywm with debug info included. the combination of swaywm 1.5.1 and wlroots 0.12.0 works best.

**Comment by lgrahl** [comment]
I'm not entirely sure I'm in the same boat here but see very similar symptoms.

> BTW, anything in dmesg?

```
kernel: nouveau 0000:03:00.0: DRM: Moving pinned object 00000000fc11445d!
kernel: nouveau 0000:03:00.0: DRM: bo 00000000e81b0ace pinned elsewhere: 0x00000001 vs 0x00000002
kernel: nouveau 0000:03:00.0: DRM: Moving pinned object 000000000520601e!
kernel: nouveau 0000:03:00.0: DRM: Moving pinned object 00000000e81b0ace!
```

526ae594 still works for me, since 754179da it does not anymore. However, this is in combination with a newer version for sway, so could be misleading. https://github.com/swaywm/wlroots/compare/526ae594...754179da
Let me know if you think this is unrelated with this issue or if I can provide more info.

**Comment by emersion** [comment]
OP's log contains:

```
00:00:00.333 [DEBUG] [backend/drm/legacy.c:95] eDP-1: failed to set hardware cursor: Device or resource busy
```

Can you try `WLR_DRM_NO_MODIFIERS=1`? Ref https://github.com/swaywm/wlroots/issues/2526

**Comment by lgrahl** [comment]
Sorry for the long delay. Yeah, that works.
