### ISSUE TITLE
Drop wlr_render_ellipse

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#2759]
Drop `wlr_render_ellipse` and `wlr_render_ellipse_with_matrix`.

This is not useful for most compositors. Compositors that want to draw ellipses can just do it manually with GL calls.

cc @bl4ckb0ne

**Comment by emersion** [comment]
cc @dos1: it seems like phoc is using it.

**Comment by dos1** [comment]
We use it for drawing touch points in a debug mode (and `wlr_render_rect` is used the same way in a damage tracking debug mode).

**Comment by emersion** [comment]
@dos1 I've submitted a pull request to drop support for ellipses: https://github.com/swaywm/wlroots/pull/2808. Does it sound reasonable to use rectangles instead of ellipses for touch point debugging? If you really want ellipses, does it sound reasonable to copy over the shader to phoc? (Just like some other compositors do for more advanced rendering features.)

**Comment by dos1** [comment]
Haven't looked yet into how using custom shaders with wlr_renderer looks like - and I'd be interested in supporting the future pixman renderer well since there are plenty of phones that could be running phoc (for instance with postmarketOS) that don't have open GLES2 drivers. However, when it comes to touch points in particular I guess we could live with rectangles there anyway.
