### ISSUE TITLE
mesa staging/21.1 error

### ISSUE THREAD

**Issue by xmixahlx** [swaywm/wlroots#2890]
with wlroots-git and sway-git on debian unstable:

mesa staging/21.0 works fine
mesa staging/21.1 provides the following error
GPU is amdgpu 5600XT
attempting to load greetd/gtkgreet

![PXL_20210425_205145251](https://user-images.githubusercontent.com/20656358/116009801-5ef7a280-a5d0-11eb-891b-2a1af87a5cf4.jpg)

**Comment by kennylevinsen** [comment]
This is a broken mesa install. What you are seeing are dynamic linker issues (undefined symbol amdgpu_query_video_caps_info), which cause all module load attempts, and thereby mesa as a whole, to fail.

This is most likely due to older dependencies still being present and taking precedence - in this particular case, most likely `libdrm_amdgpu.so`. Use `ldd` to inspect what `radeon_dri.so`'s dependencies resolve to.

**Comment by xmixahlx** [comment]
Thanks for the response. I was just about to come here and close this issue. There was a different hint to this in mesa git and I found that while mesa was building with libdrm from local it was loading libdrm from /opt/amdgpu as i have some AMD packages installed for OPENCL. the hint was amdgpu_query_video_caps_info requiring libdrm 2.4.105. Sorry for the noise here.
