### ISSUE TITLE
output freezing

### ISSUE THREAD

**Issue by ofwinterpassed** [swaywm/wlroots#2911]
Every no and when the output for my dwl instance freezes. Switching to a virtual terminal and back unfreezes the output. This is quite annoying. I have reported it as an issue in dwl and they claim to have seen the same issue in sway and other wlroots based compositors.

**Comment by emersion** [comment]
It's going to be complicated to debug without any more info. Please at least add a link to debug logs.

**Comment by greenfoo** [comment]
Hi, I'm also experiencing "freezes" randomly (in my case I'm using sway).

The issue happens **mainly** (but not exclusively) while watching YouTube videos on Firefox... and I would say once a day or less. If I run gnome instead of sway the problem disappears. 

Only the image freezes, everything else "seems" to work (ex: if I open a terminal and try to double TAB, I get the terminal "sound" for "no more completions", even if I can't see any of this because the screen is not being refreshed).

I'm on Arch, which around 1 month ago updated to 0.13.0 (see here https://github.com/archlinux/svntogit-community/commits/packages/wlroots/trunk). I would say (but I'm not 100% sure) this is also around the time I started experiencing this issue.

These are the log messages generated during the 10 last seconds before the issue was triggered: 
[error.log](https://github.com/swaywm/wlroots/files/6448470/error.log)

Let me know if I can do something to obtain better debug information.

Thanks.

**Comment by emersion** [comment]
This debug log is incomplete. Please open a new Sway issue with complete debug logs. Also attach dmesg logs.

**Comment by ahmadraniri1994** [comment]
I face the error too...

**Comment by fluix-dev** [comment]
@ahmadraniri1994 feel free to provide any extra information in #2937

**Comment by ahmadraniri1994** [comment]
@fluix-dev well, sorry for reply too late, I guess it's related with specific graphic driver's stuffs ? I have dual GPU (hybrid ?) Intel and nvidia.
