### ISSUE TITLE
backend/drm: PRIME import not supported in VirtualBox

### ISSUE THREAD

**Issue by v-byte-cpu** [swaywm/wlroots#3167]
Hi there! After upgrading wlroots, sway fails to start in VirtualBox with `PRIME import not supported` error. I guess it is related to this PR https://github.com/swaywm/wlroots/pull/2834.

**Comment by emersion** [comment]
Yeah, fix is add support for that in VirtualBox.

**Comment by v-byte-cpu** [comment]
Is it possible to add backward compatibility with systems like VirtualBox until it supports this feature ?

**Comment by emersion** [comment]
Nope, this isn't possible given the wlroots architecture.

**Comment by v-byte-cpu** [comment]
Okay, got it. However, I have found a solution to my problem running sway in VirtualBox. You should enable 3D Acceleration for Graphics Controller. Tested with VMSVGA and VBoxSVGA. Hope this will be helpful to others who are facing the same problem.

**Comment by DemiMarie** [comment]
> Okay, got it. However, I have found a solution to my problem running sway in VirtualBox. You should enable 3D Acceleration for Graphics Controller. Tested with VMSVGA and VBoxSVGA. Hope this will be helpful to others who are facing the same problem.

FYI, this is considered a security risk unless the guests are fully trusted.  One alternative would be to use a software rendering backend, if wlroots has one.

**Comment by kennylevinsen** [comment]
> FYI, this is considered a security risk unless the guests are fully trusted.

It is always a security risk to run something untrusted, even within a VM (escapes happen). The usage of VMs does not imply that the user is creating a security sandbox.

This issue is purely about getting accelerated graphics to work *again*, which is intended to be supported, not a discussion about OPs threat model. We also do not bring up security when users forward entire GPUs, as that's up to them.

Please don't comment off-topic on closed issues.
