### ISSUE TITLE
Scale rootston cursor on scaled outputs

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#401]

**Comment by emersion** [comment]
Proposal: add a `scale` parameter to `wlr_cursor_set_image`. This function for now applies the cursor image to all outputs. Change it to apply the image only to outputs having the provided scale.

That way, compositors would call `wlr_cursor_set_image` multiple times with different scale parameters instead of one time when they want to set a new cursor.

**Comment by SirCmpwn** [comment]
+1
