### ISSUE TITLE
wlroots (sway) fails to start on QEMU's VGA card

### ISSUE THREAD

**Issue by n3rdopolis** [swaywm/wlroots#456]
Hi

I compile my own Mesa, so it could be a Mesa issue? ...But other Wayland DEs work on this VM, and Sway does work on my Intel box

It seems that both the Wayland and DRM backend fail, due to not being able to find EGL extensions... ...however it does not say which egl extension it is trying to use, and I am using very recent Mesa

I have attached a screenshot of the error, along with some other output, since I don't have clipboard passing
![swayroots](https://user-images.githubusercontent.com/6219356/33518159-7d060260-d75e-11e7-92a5-7ad65c9bb020.png)

I get similar behavior with rootston

Thanks

**Comment by emersion** [comment]
It's trying to use `EGL_WL_bind_wayland_display` and `EGL_KHR_image_base`.

**Comment by n3rdopolis** [comment]
Could it be an issue with swrast? 
I'm trying to force it to use softpipe or llvmpipe...

**Comment by emersion** [comment]
>Setting LIBGL_ALWAYS_SOFTWARE=1 on my intel box where wlroots will usually work causes the same error...

I can reproduce.

**Comment by SirCmpwn** [comment]
Can no longer reproduce, I think this was fixed with my other EGL fixes

**Comment by martinetd** [comment]
I can start rootston (the grey display opens up with vga std/qxl) so there's progress compared to when the issue was started, but it's far from "good":

 * There does not seem to be any cursor/pointer events? Hmm actually clicks look like they go through but moving doesn't work, cursor is stuck where it spawned.
I'm not sure why, there are input devices and the card says it supports planes but maybe it doesn't really. There's this line that might be fishy?
```
2018-03-28 07:29:59 - [backend/drm/atomic.c:38] Atomic test failed: Numerical result out of range
```

 * gnome-terminal opens up but not urxvt, I think the culprit is this line:
```
2018-03-28 07:30:03 - [EGL] eglCreateImageKHR: (null)
```

With cirrus rootston doesn't open up at all:
```
2018-03-28 07:36:00 - [backend/drm/drm.c:730] VGA-1: Retrying pageflip
2018-03-28 07:36:00 - [backend/drm/util.c:177] Unable to add DRM framebuffer: Invalid argument
2018-03-28 07:36:00 - [backend/drm/legacy.c:15] VGA-1: Failed to set CRTC: No such file or directory
2018-03-28 07:36:00 - [backend/drm/drm.c:730] VGA-1: Retrying pageflip
2018-03-28 07:36:00 - [backend/drm/util.c:177] Unable to add DRM framebuffer: Invalid argument
2018-03-28 07:36:00 - [backend/drm/legacy.c:15] VGA-1: Failed to set CRTC: No such file or directory
in a busy loop
```

**Comment by SirCmpwn** [comment]
>gnome-terminal opens up but not urxvt, I think the culprit is this line:

I'm not sure that we can do anything about that
