### ISSUE TITLE
Add wlr_input_device_is_libinput

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#482]
And corresponding functions for wlr_output, etc

**Comment by acrisci** [comment]
The idea is to expose the actual `libinput_device` to library users so they can do the configuration on the device themselves.

Users can use [wlr_libinput_get_device_handle()](https://github.com/swaywm/wlroots/blob/master/include/wlr/backend/libinput.h) to get the `libinput_device` but this will segfault if the device is not a libinput device, hence the new function.

The requirements for libinput device configuration can be seen at the [sway-input man page](https://github.com/swaywm/sway/blob/master/sway/sway-input.5.txt). Each of these configuration options has a corresponding function in `libinput.h` to set the configuration.

Examples: `libinput_device_config_accel_set_profile()`, `libinput_device_config_click_set_method()`, `libinput_device_config_tap_set_drag_lock_enabled()`, need to be called on the raw device.

Rootston should take a similar approach in the `[device:<name>]` block.

Example:

```ini
[device:mouse1]
accel_profile=adaptive
drag_lock=disabled
click_method=button_area
```

@martinetd make sure to mention any kind of configuration you want to add to this.

**Comment by martinetd** [comment]
I'd rather keep both issues separate, as I'd do this in two PR (especially since the original comment from @SirCmpwn asks for corresponding wlr_output/etc functions which have nothing to do with libinput configuration)

That aside the plan looks good to me and corresponds to the idea I had, I'll check which configurations I depend on exactly tonight as well.
What about what I said about only doing a few arbitrary settings for rootston just to show how it should work (that'll save effort on config parsing boilerplate/adding new enums mostly)? Do you agree there or do we want to be as feature complete as possible?

**Comment by acrisci** [comment]
Yeah just do whichever ones you want to do. They'll all be pretty similar.
