### ISSUE TITLE
Chromium context menus won't show up in fullscreen mode

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#577]
Because the context menu views don't have a parent set (it works fine in Firefox).

TODO: check what i3 does.

**Comment by emersion** [comment]
We probably need `WM_CLIENT_LEADER` here.

**Comment by emersion** [comment]
Note: not working in Weston.

**Comment by Ongy** [comment]
It's a chromium bug.
It doesn't set up parent/child relationship. If we want to do this, we need to react to any window that's override redirect.

This would include dunst/dmenu which makes sense.
But the current renderstrategy would have to be reworked.
Since fullscreen X11 windows are intended to render their children as children, not independant X11 windows, and we there's no stacking order above the fullscreen view.

**Comment by emersion** [comment]
Closing because this is a rootston issue.
