### ISSUE TITLE
Cursor jumps  on decoration border enter in DRM backend

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#581]
Introduced in #570 with decoration support.

To reproduce:

Enter a decoration border. In the first few pixels of entry, the cursor resize edge xcursor will appear and upon the next move, it will "jump" to (I think) what is the correct position.

Issue is not present on the X11 or Wayland backend.

**Comment by emersion** [comment]
Can reproduce:
* Enter a surface with CSD
* Click on the titlebar without moving, the cursor changes to be a hardware one but has an invalid position (because of the hotspot)
* Move a little, the cursor jumps and now has the correct position

This happens because `crtc_move_cursor` needs to be called in `wlr_drm_connector_set_cursor` when the hotspot changes.
