### ISSUE TITLE
Screenshooter issues with output scales

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#604]
The screenshooter example doesn't work with multiple outputs with a different scale each.

Pixel buffers are just copied to the output image without scaling. This means views will look bigger on HiDPI screens in the resulting image, and more importantly some outputs can be be copied on top of each other (for instance try a scale=2 output with a scale=1 output on the right).

Fractional scaling makes this even more difficult, because the screenshooter has no way to know the real output scale. That can be solved by implementing xdg-output which provides outputs' logical position and size.

From here we have to make a decision:
* Support output scales, we'll probably need to use a proper image library to scale buffers
* Only allow to screenshot one output with the screenshooter

**Comment by Timidger** [comment]
Since this is just an example program, how complicated would adding a proper image library to handle the scales make it? I see the examples as primarily a way for new compositor writers to get up and going / serve as documentation and as a manual test suite only as a side effect of their existence.

Handling only one output would make the example less complete, but it would make it easier to communicate the work that it's trying to show off (e.g using the screenshooter API)

**Comment by Ongy** [comment]
I said it on IRc before, I'm against the screenshooter doing any unreversable image processing.

I think doing only one output makes more sense for now.
Or have it do one image per output.
So don't just have the wayland-screenshot.png, but generate one image for each output.
And then have e.g. wayland-DVI-1-screenshot.png and wayland-DVI-2-screenshot.png generated.
Getting them back together into one is easy enough with imagemagick.

**Comment by emersion** [comment]
>And then have e.g. wayland-DVI-1-screenshot.png and wayland-DVI-2-screenshot.png generated.

It's not possible to get the names of outputs, so it'll probably be `wayland-screenshot-1.png`, `wayland-screenshot-2.png` and so on.
