### ISSUE TITLE
Send frame events to surfaces unconditionally

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#644]
Right now we don't send frame events to surfaces when we're skipping the renderer. We should send those unconditionally, so clients can sync to the vblank cycle even if they don't always damage their content.

**Comment by Ongy** [comment]
Can't find the link just now, but (I think it was you) someone posted it a while ago, that weston does not send the frame callbacks directly after it renders (as we do), but in the frame callback, then waits for a while and renders with a delay.

This allows clients to render their own frame and attach it to before we render, so they can actually meet the next vblank, to reduce latency.
If we are going to split the actual render logic from sending callbacks, it would probably be a good time to implement that as well.

Iirc. the specific timing is user configured on weston, since it's not quite obvious what to pick.

**Comment by emersion** [comment]
For posterity, here's the link: https://github.com/swaywm/wlroots/issues/617#issuecomment-364594734

I'll think about it. It might require deeper changes (right now we schedule a frame on a surface commit, but we would have to change this the other way around).

**Comment by Ongy** [comment]
I don't think that part needs any change.
If we have callbacks we will be in the backend loop, since we flip (potentially with empty damage) to get our callback.


When we schedule a frame on surface commit, (instead of realising it's already scheduled) we are guaranteed that there's no surface which wants the callback atm.

The better question is if that should be a compositor or a wlroots feature.
Since the timed handler would be responsible of the swap_pending flag
