### ISSUE TITLE
Don'd draw xwayland children twice

### ISSUE THREAD

**Issue by agx** [swaywm/wlroots#673]
See https://github.com/swaywm/wlroots/pull/659#issuecomment-368308461

**Comment by emersion** [comment]
I don't think xwayland surfaces are drawn twice

**Comment by Ongy** [comment]
Hm, ok that was my mistake. I thought rootston had some logic to handle the children surfaces like the popups for xdg/wlshell.

To get the view alpha, that would be necessary over giving all of them their own view.
"Not supported on Xwayland" would be a viable answer to that as well (e.g. chromium breaks this either way, since it doesn't set parent)
