### ISSUE TITLE
Disable all disable outputs when switching back from another VT

### ISSUE THREAD

**Issue by linkmauve** [swaywm/wlroots#675]
I have this in my configuration file:
```ini
[output:LVDS-1]
enable = false
```

As expected it is disabled when I start rootston, but if I switch to another VT (there fbcon enables it again) and switch back I see it drawn in the usual gray and with backlight on.  The gray may indicate that it does get drawn even when it is disabled, which is a waste of GPU power and VRAM.

**Comment by Ongy** [comment]
It does not get drawn when disabled.
(We may schedule a draw not sure, but the frame handler skips it).

What you are observing is currently expected behaviour. Setting mode or switching tty (re)enables outputs, to keep track of what the hardware/other software does to us.
From my point of view, this is more of a feature request than a bug at the current point.

**Comment by linkmauve** [comment]
But then it doesn’t allow my pointer to go there, which may be the actual bug.

**Comment by emersion** [comment]
The DRM backend should keep track of disabled outputs, to re-disable them when the user switches VTs.

**Comment by Ongy** [comment]
Should as in does today, or as in would be the place to?

**Comment by emersion** [comment]
Should as in it's not correctly done yet.
