### ISSUE TITLE
Support override redirect flag change

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#734]
Xwayland allows mapped windows to change their override redirect flag on map_notify or configure_notify. It was reported to cause issues with VLC.

See https://patchwork.freedesktop.org/patch/211161/

**Comment by acrisci** [comment]
Do we have any steps to reproduce for a bug in rootston?

I tried VLC with Xwayland and the "view" menu is pretty messed up, but I don't know if it is caused by this issue because they are messed up in Weston as well (but in a slightly different way).

VLC uses xdg-shell now for me. It looks like a QT app.

**Comment by emersion** [comment]
We now support this.
