### ISSUE TITLE
Consider moving wlr_renderer types into types/

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#746]

**Comment by ascent12** [comment]
I think it's fine in render/, since it's so tied to what's going on in there. We don't have things like wlr_backend or wlr_session in types/.
I actually think types/ has too much going on in it, and would prefer to see a separation between wayland global types (e.g. wlr_xdg_shell) and utility types (e.g. wlr_box).

**Comment by SirCmpwn** [comment]
Agreed on all counts.
