### ISSUE TITLE
Xwayland double axis events

### ISSUE THREAD

**Issue by ascent12** [swaywm/wlroots#848]
When scrolling on an Xwayland window, sometimes there will be two axis events sent. It's not every time, but happens very frequently. It's easiest to notice on a web browser, where the page will randomly scroll a lot further than normal.

Trying a wayland application with WAYLAND_DEBUG=1, I couldn't ever get it to send more than 1 event.
Trying libinput debug_events, I also couldn't get it to have more than 1 event.
Looking at xev, I can see that there a multiple events being sent to it, so it's definitely related to Xwayland.

This affects both rootston and sway, so it's probably a wlroots problem.

**Comment by emersion** [comment]
Can you check what happens in Weston? This stuff is handled by Xwayland.

**Comment by ascent12** [comment]
I did some extra testing on an Ubuntu 17.10 computer I have.
I tried it with weston 1.12.0 and weston's current master, I couldn't reproduce it (DRM and X11 backend).
I could still reproduce it with sway/rootston, but I only tried X11.

**Comment by marienz** [comment]
The doubling only happens to the legacy button press events, the XInput axis motion event should be fine (see "xinput test").

If you're seeing this in Firefox, try if exporting MOZ_USE_XINPUT2=1 helps. It fixes the stuttering scrolling here, and I suspect the issues it previously caused aren't too bad under Xwayland and Sway (see below).

You might also see this in Chrome (I saw some bug reports indicating it also ignores the modern scroll events in some cases). I don't know if this is still the case or if there is a workaround.

As far as I know modern toolkits use the XInput 2 events so they should be fine (unless applications opt out like Firefox does).

(Firefox opts out because of [some](https://bugzilla.mozilla.org/show_bug.cgi?id=1182700) [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1170342). One of those bugs should be fixed in Xorg 1.19. The other is focus-related, and might not be too bad under Sway: the first scroll event after moving focus away from the browser and back is lost. This was a problem under some WMs with "overeager passive button grabs", but so far I'm only noticing this in Sway if I really did move focus away, which isn't too annoying.)

**Comment by emersion** [comment]
https://github.com/swaywm/wlroots/pull/970 is the first part of the fix. The second part will be to add support to `axis_discrete` events to xwayland.

**Comment by ascent12** [comment]
The fix has been merged into Xwayland.
https://gitlab.freedesktop.org/xorg/xserver/commit/cd285922cdec966825e47220b1182a57abc1ff90
