### ISSUE TITLE
Proposal: remove backend examples, rename examples to clients

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#863]
Henceforth we should wlroots compositor features in rootston and limit our examples dir to test Wayland clients. The various wlroots-leveraging examples (rotation, touch, etc) provide dubious value and are poorly written - I haven't run any of them for development reasons in some time.

This directory structure also mirrors weston.

**Comment by Timidger** [comment]
One nice thing about this examples is that it show cases specific features, eg touch or keyboard input. 

This is harder to follow in rootston, but that might just be because that code is also fairly complicated (eg someone can read it to understand how to render clients, but since it has damage tracking it might overwhelming for a developer new to wlroots).

If you want to cover that primarily with mcwayface though then that would probably provide more value than the current examples.

**Comment by emersion** [comment]
An important point is that we shouldn't remove the cat.

**Comment by SirCmpwn** [comment]
I might be more open to keeping examples around if we

1. Rewrote them to avoid that gross shared code
2. Split out the client examples into clients/

**Comment by SirCmpwn** [comment]
And of course, we cannot remove the cat.

**Comment by emersion** [comment]
>Rewrote them to avoid that gross shared code

Yeah, +1. I think small self-contained examples will bring more value.

**Comment by Timidger** [comment]
I agree, as I think that will increase their value too.

My versions of the examples in wlroots-rs are self contained, and while they have duplicate code (eg from keyboard handling) it's much easier to read since it's in one file.
