### ISSUE TITLE
x11 backend: rootston does not exit after closing (all) outputs

### ISSUE THREAD

**Issue by psychon** [swaywm/wlroots#868]
In commit f133170ff0187247b13c227bd2527a273c54f13f, rootston exits after closing the only X11 window.
Then, in the range d4f7ced6e260961f701f73f672fffa87ee333c3d until 96c6091f802c803ccd6c7acd3e1165f6a8d4da2d, the window does not even close. This means this was introduced in d4f7ced6e260961f701f73f672fffa87ee333c3d (which removes a call to `wl_display_terminate` and replaces it with a call to `wlr_output_destroy`).
This behaviour is fixed with 37aae0b2cdebeba10f141b8646886614e1646530, but rootston keeps running and does not exit.

Now obviously, under the X11 backend, after all outputs are destroyed, no new ones will appear. Who is responsible for exiting in this case and how?

**Comment by emersion** [comment]
>Now obviously, under the X11 backend, after all outputs are destroyed, no new ones will appear.

That's not true, outputs can be added at runtime (for example with a custom command, and in the future Sway will have a built-in command for that).

This behaviour is also consistent with what the DRM backend does. I wonder if there's a better way to handle this case.

**Comment by psychon** [comment]
At least for me, I was surprised that closing the window no longer caused way-cooler to exit. Thus, I asked `gdb` to figure out where the deadlock was, but failed. ;-)

For the DRM case, I guess "an output disappears" corresponds to physically unplugging something. Thus, I can replug things easily. I guess for the x11 backend, a backend-specific function needs to be called to open a new window / create a new output. Since way-cooler (currently) uses `wlr_backend_autocreate`, it will likely not call that function.

**Comment by emersion** [comment]
>At least for me, I was surprised that closing the window no longer caused way-cooler to exit.

Ahah, I acknowledge that this change is surprising if you're used to the old behaviour.

>Since way-cooler (currently) uses wlr_backend_autocreate, it will likely not call that function.

This behaviour can be implemented in Way-Cooler directly if you like it, but we probably don't want to force anything on the wlroots side. Also, it'll be harder to implement in the future since one would be able to spin up a DRM and an X11 backend at the same time. In this case, you probably don't want the compositor to exit when there are no more outputs.

So you probably want to detect if there's a DRM backend running, and if that's not the case, exit. For this you'll need #816.

**Comment by ascent12** [comment]
Yeah, I find the "doesn't exit on all windows closed" behaviour to be a bit surprising as well. It betrays normal expectations. If the compositor is not launched from a terminal, it can actually lead to a resource leak as well.
And at the same time, people don't expect compositors or Xorg to close when all of their monitors are unplugged.

I'm fine with "inconsistent" behaviour, if it's to match people's expectations.

**Comment by SirCmpwn** [comment]
This is indeed something that other compositors should implement themselves if they wish. However, I do not wish to implement it on rootston nor sway, because it would make it difficult to test that the compositors are well-behaved with zero outputs. Surprising as it may be, this is the correct behavior.
